GET http://localhost:3001/api/overlapResult

###
GET http://localhost:3001/api/overlapResult/3

###
POST http://localhost:3001/api/overlapResult
Content-Type: application/json

{
    "fundOne": "TEST",
    "fundTwo": "MIDDLEWARE",
    "overlap": [
        "Ticker#10",
        "Ticker#20"
    ],
    "expand": false
}