GET http://localhost:3001/api/overlapResult

###
GET http://localhost:3001/api/overlapResult/unknown

###
POST http://localhost:3001/api/overlapResult
Content-Type: application/json

{
    "fundName": "TEST-ANOTHER",
    "overlap": [
        "Ticker#10",
        "Ticker#20"
    ],
    "expand": false,
    "queryMode": "2"
}